[deps]
Boltz = "4544d5e4-abc5-4dea-817f-29e4c205d9c8"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralLyapunov = "61252e1c-87f0-426a-93a7-3cdb1ed5a867"
NeuralLyapunovProblemLibrary = "83723521-ca9c-4edc-8e64-505178d150fe"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[compat]
Boltz = "1.2"
ComponentArrays = "0.15"
ControlSystemsBase = "1.14.4"
Documenter = "1"
DocumenterCitations = "1.3"
Lux = "1.2"
NeuralLyapunov = "0.2"
NeuralLyapunovProblemLibrary = "0.0"
NeuralPDE = "5.17"
Optimization = "4, 5"
OptimizationOptimJL = "0.4"
OptimizationOptimisers = "0.3"
OrdinaryDiffEq = "6.91"
Plots = "1.40.9"
SciMLBase = "2.85"
StableRNGs = "1.0"
julia = "1.11"
